### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by Vikram1234567** [system32uwu/sushi-night#2]
Help please

**Comment by system32uwu** [comment]
Can you develop your issue? What do you need help with?

There's currently a binary for AOSP based OSs (Android), have you faced any problem running it?

**Comment by Tetous** [comment]
how do you connect the sushi api to this? Iike for the website

**Comment by system32uwu** [comment]
Do you mean sushi-night-backend? You need to deploy it to some hosting site that accepts node.js, like heroku ([just like I have it](https://sushi-night-backend.herokuapp.com/api)).

Once you have a URL you need to replace line 97 in [src/util/index.js](https://github.com/system32uwu/sushi-night/blob/main/src/util/index.js#L97), for the endpoint of your API.

If you are testing however that is not necessary, the url that's already there is already working.

@Vikram1234567 is this what you were asking for?

**Comment by system32uwu** [comment]
I'm closing this, if you have an specific question please open a new issue detailing what you need help with.
